run ../common/login.http


### Create group
< {%
    client.global.set("groupName", $random.name["title"])
%}

POST {{baseUrl}}/groups
Content-Type: application/json

{
  "name": "{{groupName}}"
}

> {%
    client.test("create group", () => {
        client.assert(response.status == 200)
    })
    client.global.set("groupId", response.body.id)
%}


### Get group info
GET {{baseUrl}}/groups/{{groupId}}
Accept: application/json

> {%
    client.test("group info", () => {
        client.assert(response.status == 200, "status ok")
        client.assert(response.body["name"] == client.global.get("groupName"))
    })
%}


### Get list of groups
GET {{baseUrl}}/groups
Accept: application/json


### List Group Members
GET {{baseUrl}}/groups/{{groupId}}/members
Accept: application/json


### Add member
POST {{baseUrl}}/groups/{{groupId}}/members
Content-Type: application/json

{ "name": "alt1" }